Repository googleapis/nodejs-recommender, pull requests merged in 2020-07, with the labels that each got.

#90 build: use bazel build
  protos/google/cloud/recommender/v1/insight.proto
  protos/google/cloud/recommender/v1/recommendation.proto
  protos/google/cloud/recommender/v1/recommender_service.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/recommender_client.ts
  src/v1/recommender_client_config.json
  src/v1/recommender_proto_list.json
  synth.metadata
  synth.py
  test/gapic_recommender_v1.ts
  webpack.config.js
Labels: automerge, cla: yes

#91 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#94 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#98 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#101 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#102 build: missing closing paren in publish script, delete template for Node 8, add config files for cloud-rad
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#103 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#104 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#105 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full, kokoro:run

#106 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#107 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none
